affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
env:
  api:
    domainsAPIEnabled: true
    pnpAPIEnabled: true
  blockchain:
    blockchainApiKeyExistingSecret: odis-signer1-forno-key
    blockchainProvider: https://forno.celo.org
  db:
    cloudSqlProxy: false
    database: phoneNumberPrivacy
    host: odis-signer1-mainnet-db-postgresql-hl
    passwordExistingSecret: odis-signer1-db-password
    port: 5432
    type: postgres
    useSsl: false
    username: clabs
  keystore:
    domainsKeyLatestVersion: null
    domainsKeyNameBase: odis-signer1-mainnet-domains
    gcp:
      projectID: celo-testnet-production
    pnpKeyLatestVersion: null
    pnpKeyNameBase: odis-signer1-mainnet-phoneNumberPrivacy
    type: GoogleSecretManager
  log:
    format: stackdriver
    level: trace
  odis:
    odisSignerTimeout: "6000"
    shouldMockAccountService: "false"
    shouldMockRequestService: "false"
    testQuotaBypassPercentage: "50"
  tracing:
    enabled: true
    endpoint: "http://grafana-agent.monitoring:14268/api/traces"
    serviceName: "odis-signer1-mainnet-k8s"
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: us.gcr.io/celo-testnet/celo-monorepo
  tag: oblivious-decentralized-identifier-service-3.0.1
imagePullSecrets: []
ingress:
  annotations: {}
  className: nginx
  enabled: false
  hosts: []
  tls: []
livenessProbe: {}
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
readinessProbe: {}
replicaCount: 1
resources: {}
securityContext: {}
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: odis-signer1-mainnet@celo-testnet-production.iam.gserviceaccount.com
  create: true
  name: ""
tolerations: []
