coverage:
  status:
    project:
      default:
        target: auto
        threshold: null
        removed_code_behavior: adjust_base
      packages:
        paths:
          - packages/
      apps:
        paths:
          - apps/
    patch: off
