##### Gathering dependencies
FROM scratch AS packages

# Copy phone-number-privacy package and its dependency closure.
# Assemble all dependencies into the packages folder so the second stage can select whether to
# include all packages, or just the phone-number-privacy packages.
WORKDIR /celo-phone-number-privacy/
COPY apps/combiner apps/combiner
COPY apps/signer apps/signer
COPY packages/common packages/common
COPY packages/encrypted-backup packages/encrypted-backup
COPY packages/identity packages/identity
COPY packages/odis-identifiers packages/odis-identifiers

##### Main stage
FROM node:18
LABEL org.opencontainers.image.authors="devops@clabs.co"

WORKDIR /celo-phone-number-privacy/

# Copy monorepo settings
COPY .yarnrc.yml package.json yarn.lock ./
COPY .yarn/releases/ .yarn/releases/

# Makes build fail if it doesn't copy git, will be removed after build
COPY .git .git

ARG PACKAGE_SELECTOR=combiner
# COMMENT OUT THIS LINE TO USE PUBLISHED DEPENDENCIES
COPY --from=packages celo-phone-number-privacy/packages/ packages/
COPY --from=packages celo-phone-number-privacy/apps/${PACKAGE_SELECTOR} apps/${PACKAGE_SELECTOR}

# Install dependencies and build.
RUN yarn workspaces focus @celo/phone-number-privacy-combiner  --inline-builds && yarn cache clean
RUN yarn workspaces list
# delete tests so they dont get built because signer is needed by them
RUN rm -rf apps/combiner/test
RUN yarn workspaces foreach -ipv --topological-dev  -R --from @celo/phone-number-privacy-combiner run build

RUN rm -r .git

# Setup and run the combiner application.
ENV NODE_ENV production
WORKDIR /celo-phone-number-privacy/apps/combiner
EXPOSE 8080
ENTRYPOINT ["yarn", "start:docker"]
