##### Gathering dependencies
FROM scratch AS packages

# Copy phone-number-privacy package and its dependency closure.
# Assemble all dependencies into the packages folder so the second stage can select whether to
# include all packages, or just the phone-number-privacy packages.
WORKDIR /celo-phone-number-privacy/
COPY odis/combiner odis/combiner
COPY odis/signer odis/signer
COPY packages/common packages/common
COPY packages/encrypted-backup packages/encrypted-backup
COPY packages/identity packages/identity
COPY packages/odis-identifiers packages/odis-identifiers

##### Main stage
FROM node:18
LABEL org.opencontainers.image.authors="devops@clabs.co"

WORKDIR /celo-phone-number-privacy/

# Copy monorepo settings
COPY .yarnrc.yml package.json yarn.lock ./
COPY .yarn/releases/ .yarn/releases/

# Makes build fail if it doesn't copy git, will be removed after build
COPY .git .git

ARG PACKAGE_SELECTOR=combiner
# COMMENT OUT THIS LINE TO USE PUBLISHED DEPENDENCIES
COPY --from=packages celo-phone-number-privacy/packages/ packages/
COPY --from=packages celo-phone-number-privacy/odis/${PACKAGE_SELECTOR} odis/${PACKAGE_SELECTOR}

# delete tests so they dont get built because signer is needed by them,
RUN rm -rf odis/combiner/test
# remove signer dep as its only used in tests and we dont want to build it
RUN yarn --cwd=odis/combiner remove @celo/phone-number-privacy-signer
# Install dependencies and build.

RUN yarn install --network-timeout 100000  --inline-builds && yarn cache clean
RUN yarn workspaces list

RUN yarn workspaces foreach -ipv --topological-dev  -R --from @celo/phone-number-privacy-combiner run build
# once we are built trim down the dependencies
RUN yarn workspaces focus @celo/phone-number-privacy-combiner --production
RUN rm -r .git

# Setup and run the combiner application.
ENV NODE_ENV production
WORKDIR /celo-phone-number-privacy/odis/combiner
EXPOSE 8080
RUN yarn
ENTRYPOINT ["yarn", "start:docker"]
