---
name: Build ODIS combiner image

on:
  push:
    paths:
      - 'dockerfiles/phone-number-privacy/Dockerfile-combiner'
      - 'packages/phone-number-privacy/combiner/**'
    branches:
      - main
  pull_request:
    paths:
      - 'dockerfiles/phone-number-privacy/Dockerfile-combiner'
      - 'packages/phone-number-privacy/combiner/**'
  workflow_dispatch:

jobs:
  odis-combiner-build-dev:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.12.2
    name: Build us-west1-docker.pkg.dev/devopsre/dev-images/odis-combiner
    if: |
      github.ref != 'refs/heads/main'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-social-connect/providers/github-by-repos
      service-account: 'social-connect-dev@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/dev-images/odis-combiner
      tag: ${{ github.sha }}
      context: .
      file: dockerfiles/phone-number-privacy/Dockerfile-combiner
      trivy: true

  odis-combiner-build:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v1.12.2
    name: Build us-west1-docker.pkg.dev/devopsre/social-connect/odis-combiner
    if: |
      github.ref == 'refs/heads/main'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-social-connect-main/providers/github-by-repos
      service-account: 'social-connect@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/social-connect/odis-combiner
      tag: ${{ github.sha }}
      context: .
      file: dockerfiles/phone-number-privacy/Dockerfile-combiner
      trivy: true
