---
name: Build ODIS combiner image

on:
  push:
    paths:
      - 'dockerfiles/Dockerfile-combiner'
      - 'apps/combiner/**'
      - 'yarn.lock'
    branches:
      - main
      - 'prerelease/*'
    tags:
      - odis-combiner-.*
  pull_request:
    paths:
      - 'dockerfiles/Dockerfile-combiner'
      - 'apps/combiner/**'
      - 'yarn.lock'
  workflow_dispatch:

jobs:
  odis-combiner-build-dev:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v2.0.5
    name: Build us-west1-docker.pkg.dev/devopsre/dev-images/odis-combiner
    if: |
      github.ref != 'refs/heads/main'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-social-connect/providers/github-by-repos
      service-account: 'social-connect-dev@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/dev-images/odis-combiner
      tags: ${{ github.sha }}
      context: .
      file: dockerfiles/Dockerfile-combiner
      trivy: true

  odis-combiner-build:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v2.0.5
    name: Build us-west1-docker.pkg.dev/devopsre/social-connect/odis-combiner
    if: |
      github.ref == 'refs/heads/main'
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-social-connect-main/providers/github-by-repos
      service-account: 'social-connect@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/social-connect/odis-combiner
      tags: ${{ github.sha }}
      context: .
      file: dockerfiles/Dockerfile-combiner
      trivy: true

  odis-combiner-tag:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd.yaml@v2.0.5
    name: Build us-west1-docker.pkg.dev/devopsre/social-connect/odis-combiner tag
    if: |
      startsWith(github.ref, 'refs/tags/odis-combiner-')
    with:
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-social-connect-tag/providers/github-by-repos
      service-account: 'social-connect@devopsre.iam.gserviceaccount.com'
      artifact-registry: us-west1-docker.pkg.dev/devopsre/social-connect/odis-combiner
      tags: ${{ github.ref_name }}
      context: .
      file: dockerfiles/phone-number-privacy/Dockerfile-combiner
      trivy: true
