name: Release

on:
  push:
    branches:
      - main
      - 'prerelease/*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Open Release PR or Publish Packages
    permissions:
      contents: write
      actions: read
      pull-requests: write
      security-events: write
      attestations: write
      id-token: write
      repository-projects: write
    uses: celo-org/reusable-workflows/.github/workflows/npm-publish.yaml@develop-npm-publishing-oidc
    with:
      node-version: 22
      version-command: yarn version_and_reinstall
      publish-command: yarn release
